# Generated by Django 5.2.1 on 2025-05-21 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcategoryFilters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='SubcategoryFiltersValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subcategoryFilters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subcategoryfilters')),
            ],
        ),
    ]
