# Generated by Django 5.2.1 on 2025-05-22 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_subcategoryfilters_subcategoryfiltersvalues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoryfiltersvalues',
            name='subcategoryFilters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategoryFiltersValues', to='product.subcategoryfilters'),
        ),
    ]
