# Generated by Django 5.2.1 on 2025-06-02 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_subcategoryfiltersvalues_subcategoryfilters'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProductFilters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductFilters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupProductFilters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.groupproductfilters')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('subcategoryFilters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productFilters', to='product.subcategoryfilters')),
                ('subcategoryFiltersValues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subcategoryfiltersvalues')),
            ],
        ),
    ]
