# Generated by Django 5.2.1 on 2025-05-22 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyers',
            name='name',
        ),
    ]
